# -*- coding: utf-8 -*-
"""Telecom Customer Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rAMxStq0UWcS068cpUK6SfiapmUb6Lpq
"""

pip install pandas

pip install matplotlib

pip install seaborn

#importing the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

#uploading the dataset
#To begin the analysis, we first imported the Telecom Customer Churn dataset into a Pandas DataFrame.
df = pd.read_csv('telecom_customer_churn.csv')
df

#selecting fot top 5 datas
df.head(6)

## Understand the dataset using info() fuction
#The info() function gives us a quick summary — like how many columns there are, what kind of data they hold, and if anything is missing.
#From this, we get a clear idea of which parts of the data need cleaning and what we’re working with before going deeper.

df.info()

# checking the null values
#Before we dive into analysis, it’s important to check if any parts of the data are missing.
#Missing values can affect results, so let’s see where the gaps are using isnull().sum()
#Now we know which columns have missing data. This helps us decide what to fix or fill in so our analysis stays accurate.


df.isnull().sum()

# filling the null values using fillna() function
# We found that the 'alert' column had some missing values.
#To fix that, we filled those gaps using the most common value (mode) in the column — a quick way to keep things consistent.

df["Offer"]=df["Offer"].fillna(df["Offer"].mode()[0])
df["Churn Category"]=df["Churn Category"].fillna(df["Churn Category"].mode()[0])
df["Churn Reason"]=df["Churn Reason"].fillna(df["Churn Reason"].mode()[0])

#Drop the Null values in more than 80% Nullvalues
df.dropna(inplace=True)

#Finding the any duplicate rows in the dataset
df.duplicated().sum()

#checking the outliers
#To spot any unusual or extreme values (outliers), we use df.describe().
#This gives us a quick statistical summary — like the minimum, maximum, and average — so we can see if anything looks out of place.

df.describe()

"""# Gender Distribution"""

#Create the Count plot for Gender Distributon
plt.figure(figsize=(5,4))
sns.countplot(x='Gender', data=df)
plt.title("Gender Distribution")
plt.show()

"""# Marital Status Distribution"""

#Create the Count plot for Marital Status Distribution
plt.figure(figsize=(5,4))
sns.countplot(x='Married', data=df)
plt.title("Marital Status Distribution")
plt.show()

"""# Age Distribution of Customers"""

#Create the Histplot for Age Distributon of Customers
plt.figure(figsize=(6,4))
sns.histplot(df['Age'], kde=True, bins=30, color='skyblue')
plt.title("Age Distribution of Customers")
plt.show()

"""# Tenure Distribution by Customer Status"""

#Create the Histplot for Tenure Distributon by Customer Status
plt.figure(figsize=(7,4))
sns.histplot(data=df, x='Tenure in Months', hue='Customer Status', kde=True, bins=40, palette='coolwarm')
plt.title("Tenure Distribution by Customer Status")
plt.show()

"""# Contract Type vs Churn"""

#Create the Count plot for Contract Type Vs Churn
plt.figure(figsize=(6,4))
sns.countplot(x='Contract', hue='Customer Status', data=df, palette='viridis')
plt.title("Contract Type vs Churn")
plt.show()

"""# Payment Method Distribution"""

#Create the Count plot for Payment Method Distributon
plt.figure(figsize=(8,4))
sns.countplot(y='Payment Method', data=df, order=df['Payment Method'].value_counts().index, palette='crest')
plt.title("Payment Method Distribution")
plt.show()

"""# Internet Service Type vs Churn"""

#Create the Count plot for Internet Service type vs Churn
plt.figure(figsize=(6,4))
sns.countplot(x='Internet Service', hue='Customer Status', data=df, palette='rocket')
plt.title("Internet Service Type vs Churn")
plt.show()

"""# Monthly Charge by Contract Type"""

#Create the Boxplot for Monthly Charge by Contract type
plt.figure(figsize=(6,4))
sns.boxplot(x='Contract', y='Monthly Charge', data=df, palette='mako')
plt.title("Monthly Charge by Contract Type")
plt.show()

"""# Monthly Charge vs Total Revenue"""

#Create the Scatterplot for Monthly Charge vs Total Revenue
plt.figure(figsize=(6,4))
sns.scatterplot(x='Monthly Charge', y='Total Revenue', hue='Customer Status', data=df, palette='coolwarm')
plt.title("Monthly Charge vs Total Revenue")
plt.show()

"""# Top 10 Cities by Churn Count"""

#Top 10 Cities by Churn Count
v=df[df['Customer Status'] == 'Churned']
g=v.groupby('City')['Customer Status'].count()
top_cities=g.sort_values(ascending=False).head(10)

plt.figure(figsize=(8,4))
sns.barplot(x=top_cities.values, y=top_cities.index, palette='flare')
plt.title("Top 10 Cities by Churn Count")
plt.xlabel("Number of Churned Customers")
plt.show()

"""# Churn Category Distribution"""

a=df[df['Customer Status']=='Churned']
g=v.groupby('Churn Category')['Customer Status'].count()

plt.figure(figsize=(5, 3))
sns.countplot(x='Churn Category', data=df, hue='Gender')
plt.title("Top 10 Churn Reasons")
plt.xlabel("Churn Category")
plt.ylabel("Number of Customers")
plt.xticks(rotation=45)
plt.show()

"""# Top 10 Churn Reasons"""

b=df[df['Customer Status']=='Churned']
g=v.groupby('Churn Reason')['Customer Status'].count()
top_reasons=g.sort_values(ascending=False).head(10)

plt.figure(figsize=(8,6))
sns.barplot(x=top_reasons.values, y=top_reasons.index, palette='mako')
plt.title("Top 10 Churn Reasons")
plt.xlabel("Number of Customers")
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns

fig, axes = plt.subplots(4, 3, figsize=(18, 14))

# Plot 1: Gender Distribution
sns.countplot(x='Gender', data=df, ax=axes[0, 0])
axes[0, 0].set_title("Gender Distribution")

# Plot 2: Marital Status Distribution
sns.countplot(x='Married', data=df, ax=axes[0, 1])
axes[0, 1].set_title("Marital Status Distribution")

# Plot 3: Age Distribution of Customers
sns.histplot(df['Age'], kde=True, bins=30, color='skyblue', ax=axes[0, 2])
axes[0, 2].set_title("Age Distribution of Customers")

# Plot 4: Tenure Distribution by Customer Status
sns.histplot(data=df, x='Tenure in Months', hue='Customer Status', kde=True, bins=40, palette='coolwarm', ax=axes[1, 0])
axes[1, 0].set_title("Tenure Distribution by Customer Status")

# Plot 5: Contract Type vs Churn
sns.countplot(x='Contract', hue='Customer Status', data=df, palette='viridis', ax=axes[1, 1])
axes[1, 1].set_title("Contract Type vs Churn")

# Plot 6: Payment Method Distribution
sns.countplot(y='Payment Method', data=df, order=df['Payment Method'].value_counts().index, palette='crest', ax=axes[1, 2])
axes[1, 2].set_title("Payment Method Distribution")

# Plot 7: Internet Service Type vs Churn
sns.countplot(x='Internet Service', hue='Customer Status', data=df, palette='rocket', ax=axes[2, 0])
axes[2, 0].set_title("Internet Service Type vs Churn")

# Plot 8: Monthly Charge by Contract Type
sns.boxplot(x='Contract', y='Monthly Charge', data=df, palette='mako', ax=axes[2, 1])
axes[2, 1].set_title("Monthly Charge by Contract Type")

# Plot 9: Monthly Charge vs Total Revenue
sns.scatterplot(x='Monthly Charge', y='Total Revenue', hue='Customer Status', data=df, palette='coolwarm', ax=axes[2, 2])
axes[2, 2].set_title("Monthly Charge vs Total Revenue")

# Plot 10: Top 10 Cities by Churn Count
v = df[df['Customer Status'] == 'Churned']
g = v.groupby('City')['Customer Status'].count()
top_cities = g.sort_values(ascending=False).head(10)
sns.barplot(x=top_cities.values, y=top_cities.index, palette='flare', ax=axes[3, 0])
axes[3, 0].set_title("Top 10 Cities by Churn Count")
axes[3, 0].set_xlabel("Number of Churned Customers")


# Plot 11: Churn Category Distribution
a = df[df['Customer Status']=='Churned']
g = a.groupby('Churn Category')['Customer Status'].count()
sns.countplot(x='Churn Category', data=df, hue='Gender', ax=axes[3, 1])
axes[3, 1].set_title("Churn Category Distribution")
axes[3, 1].set_xlabel("Churn Category")
axes[3, 1].set_ylabel("Number of Customers")
axes[3, 1].tick_params(axis='x', rotation=45)

# Plot 12: Top 10 Churn Reasons
b = df[df['Customer Status']=='Churned']
g = b.groupby('Churn Reason')['Customer Status'].count()
top_reasons=g.sort_values(ascending=False).head(10)
sns.barplot(x=top_reasons.values, y=top_reasons.index, palette='mako', ax=axes[3, 2])
axes[3, 2].set_title("Top 10 Churn Reasons")
axes[3, 2].set_xlabel("Number of Customers")

plt.tight_layout()
plt.show()

"""# Final Summary"""

print("\nGender Distribution - Male-Female")
print("\nMarital Status Distribution - NO")
print("\nAge Distribution of Customers - 20-70-80")
print("\nTenure Distribution by Customer Status - 0-10")
print("\nContract Type vs Churn - Month-to-Month")
print("\nPayment Method Distribution -  Bank Withdrawl")
print("\nInternet Service Type vs Churn - Yes")
print("\nMonthly Charge by Contract Type - M-to-M, Two Years")
print("\nMonthly Charge vs Total Revenue - 80-120/10,000")
print("\nTop 10 Cities by Churn Count")
print("\nChurn Category Distribution - Competitor")
print("\nTop 10 Churn Reasons")
print("\nEnd of Summary")